
main: me.ice.ASMP2.Main
name: ASMP2
version: 1.0
author: CelluronTech

commands:
  civinvite:
  civcreate:
  civremove:
  civkick:
  civlist:
  civtypes:
  civinfo:
  civrename:
  civchangecolor:
  civleave:
  civtransfer:
  civmedia:
  civcolors:
  civdisband:
  civtester:
  civclear:
  civaccept:
  civdeny:
  media:
  civAbil1:
  civLevelUp:
    permission: level.up
permissions:
  level.up:
    description: allows levelup command
    default: op
