main: me.ice.ASMP2.Main
name: ASMP2
version: 1.0
author: CelluronTech

commands:
  civ:
  help:
  media:

# Developer commands used for testing abilities
  testability:
    description: Used for testing civilization abilities.
    aliases: [ta]
