main: me.ice.ASMP2.Main
name: ASMP2
version: 1.0
author: CelluronTech

commands:
  civ:
  help:
  media:

# Developer commands used for testing abilities
  testabilityblockthrow:
    description: Used for testing block throw ability.
    usage: "Usage: /testabilityblockthrow <x> <y> <z>"
    aliases: [tabt]
